import os
import time
os.system('clear')
print ('╔═══╗─────╔═══╦╗────────╔╗──────╔╗ ')
print ('║╔═╗║─────║╔═╗║║───────╔╝╚╗─────║║ ')
print ('║╚══╦══╦═╗║╚══╣╚═╦══╦═╗╚╗╔╬══╦══╣║ ')
print ('╚══╗║╔╗║╔╝╚══╗║╔╗║╔╗║╔╝─║║║╔╗║╔╗║║ ')
print ('║╚═╝║╚╝║║─║╚═╝║║║║╔╗║║──║╚╣╚╝║╚╝║╚╗ ')
print ('╚═══╩══╩╝─╚═══╩╝╚╩╝╚╩╝──╚═╩══╩══╩═╝ ')
print                           ('version 1.0')
time.sleep(1)
print ('Author=>YeMinAung ')
time.sleep(1)
print ('Facebook=>https://facebook.com/MinMaySatPatMoLoLinkKoCopyTrLar')
time.sleep(1)
gf=input('Input the girl name you love : ')
yn=input('Your Name Mother Fucker : ')
time.sleep(3)
print ('[+]Was your Girlfriend name was ' +gf )
time.sleep(2)
print ('[+]Hey Motherfucker Was this your realname? ' +yn)
time.sleep(3)
input ('[+]All The Things are correct?Mother fucker say yes : ')
time.sleep(3)
print ('Your enter yes!')
time.sleep(2)
os.system ('clear')

print ('╔═══╗ ')
print ('║╔═╗║ ')
print ('║║─║╠═╗╔══╦╗╔╗╔╦══╦═╗ ')
print ('║╚═╝║╔╗╣══╣╚╝╚╝║║═╣╔╝ ')
print ('║╔═╗║║║╠══╠╗╔╗╔╣║═╣║ ')
print ('╚╝─╚╩╝╚╩══╝╚╝╚╝╚══╩╝ ')
print ('your answer is ')
time.sleep(4)
print ('[+]LEE MIN D TA THET SAW YA MHAR MA HOTE BUU SORRY BRO' ,yn )


print ('bye ')
os.system('exit')

